@startuml

agent "App" as app
rectangle CD {
  agent "Backend App" as backendapp
  agent "PagoPA proxy" as pagopaproxy
}
rectangle PagoPA {
  agent "Nodo PagoPA" as nodopagopa
}

app -> backendapp : (1) Numero avviso
backendapp -> pagopaproxy : (2) Numero avviso
pagopaproxy -> nodopagopa : (3) Numero avviso


@enduml