@startuml

agent "App" as app
rectangle CD {
  agent "Backend App" as backendapp
  agent "PagoPA proxy" as pagopaproxy
}
rectangle PagoPA {
  agent "Nodo PagoPA" as nodopagopa
  agent "Wallet" as wallet
}

app -> backendapp : (1) Numero avviso
backendapp -> pagopaproxy : (1) Numero avviso
pagopaproxy -d-> nodopagopa : (1) Numero avviso

nodopagopa -> pagopaproxy : (2) ID pagamento
backendapp -> pagopaproxy : (3) ID pagamento?
app -> backendapp : (3) ID pagamento?

app -d-> wallet : (4) ID pagamento
wallet <-> nodopagopa : "(5)"

@enduml