@startuml

actor Cittadino

agent Smartphone

cloud "Regione Azure" {
  rectangle "Load balancer" as azurelb
  node "Virtual Machines" as azurevm
  rectangle "Appliance VPN" as azurevpn
}

cloud "PagoPA" {
  rectangle "Appliance VPN" as pagopavpn
  node "Server PagoPA" as pagopavm
}

cloud "Ente" {
  node "Server Servizio" as serviziovm
}

cloud "Provider email" {
  node "Server email" as emailvm
}

Cittadino .r. Smartphone

Smartphone --> pagopavm
Smartphone ---> azurelb

serviziovm -u-> azurelb

azurelb -r-> azurevm
azurevpn -l-> azurevm

pagopavpn -d-> azurevpn

pagopavpn -l-> pagopavm

azurevm --> emailvm

@enduml