@startuml

rectangle Ente {
  actor "Responsabile\ndel servizio" as respservizio
  agent Servizio as servizio
}
rectangle "CD" {
  rectangle APIM {
    agent "API Gateway" as apigw
    agent "Developer\nportal" as devportal
    database "Chiavi API e\nruoli associati" as keydb
  }
  agent "API CD" as apicd
}

respservizio <-> devportal : (1) accreditamento
devportal -> keydb : (1) ID servizio,\nchiave API, ruoli
respservizio -d-> servizio : (2) chiave API

servizio -> apigw : (3) chiave API
keydb -d-> apigw : (4) ID servizio, ruoli
apigw --> apicd : (5) ID servizio, ruoli

@enduml