@startuml

actor Cittadino

agent Smartphone

cloud {
  node "Datacenter CD primario" as cddcp
}

cloud {
  node "Datacenter CD secondario" as cddcs
}

cloud {
  node "Datacenter SIA SpA" as siadc
}

cloud {
  node "Datacenter Ente" as entedc
}

Cittadino . Smartphone

Smartphone ---> cddcp
Smartphone ---> cddcs
Smartphone -> siadc

cddcp <=right=> cddcs

siadc <===> cddcp
siadc <===> cddcs

entedc ---> cddcp
entedc ---> cddcs


@enduml