@startuml

agent "App" as app

cloud "Cittadinanza Digitale" {

  agent "italia-backend" as backend
  agent "italia-pagopa-proxy" as pagopaproxy
  agent "API CD" as apicd
}

cloud "PagoPA" {

  agent Wallet as pagopawallet
  agent Nodo as pagopanodo

}

agent "Servizio Ente" as servizio

node MailUp

node MixPanel

servizio -> apicd

apicd <-> backend

app -u-> backend
app -> pagopawallet

backend -> pagopaproxy
pagopaproxy <--> pagopanodo

pagopawallet <-> pagopanodo

apicd -d-> MailUp

app -d-> MixPanel

@enduml