@startuml

rectangle Ente {
  agent "Servizio\npresso\nente" as ente
}

rectangle "Cittadinanza Digitale" {
  agent "API Messaggi" as apimessaggi
}

:Cittadino: as cittadino

ente --> apimessaggi : messaggio,\nCF

note right of apimessaggi
  L'API Messaggi di Cittadinanza Digitale
  non ha modo di contattare il cittadino
  per cui il messaggio viene ignorato ed
  eliminato.
end note

@enduml
