@startuml

rectangle "Ente Erogatore" {
  agent "Servizio" as ente
}

rectangle "Cittadinanza Digitale" {
  agent "API Messaggi" as apimessaggi
}

:Cittadino: as cittadino

ente -d-> apimessaggi : (1) CF, messaggio

note right of apimessaggi
  (2) L'API Messaggi di Cittadinanza Digitale
  non ha modo di contattare il cittadino
  per cui il messaggio viene ignorato ed
  eliminato.
end note

@enduml
