activate SAS
SAS -> "API gateway": send message request
activate "API gateway"
"API gateway" -> "API Functions": forward message
activate "API Functions"
"API Functions" -> "Database": save message
activate "Database"
"Database" -> "API Functions": message saved
deactivate "Database"
"API Functions" -> "API gateway": return message
"API gateway" -> "SAS": return queued message id
deactivate "API gateway"
deactivate SAS
"API Functions" -> "Notification queue": map message to notification
deactivate "API Functions"
activate "Notification queue"
"Notification queue" -> "API Functions": trigger notification function
deactivate "Notification queue"
activate "API Functions"
"API Functions" -> "Channel queue": dispatch notification to channel
deactivate "API Functions"
activate "Channel queue"
"Channel queue" -> "API Functions": trigger channel function
deactivate "Channel queue"
activate "API Functions"
"API Functions" -> "Channel": send notification to channel
activate "Channel"
"Channel" -> "API Functions": return notification status
deactivate "Channel"
activate "Database"
"API Functions" -> "Database": save notification status
deactivate "API Functions"
deactivate "Database"
